"""
Configuration for Shopify → Softland daily sync.
Copy this file and fill values on the client machine, or set environment variables.
"""
from __future__ import annotations

import os
from pathlib import Path

# --- Paths ---
# Root of this project (folder containing main.py)
PROJECT_ROOT = Path(__file__).resolve().parent

# Log file
LOG_FILE = PROJECT_ROOT / "automation.log"

# Calibration output (generated by calibrate.py)
COORDS_FILE = PROJECT_ROOT / "coords_captured.json"

# Processed Shopify order IDs (duplicate protection)
PROCESSED_ORDERS_FILE = PROJECT_ROOT / "processed_orders.json"

# --- Shopify Admin API ---
# Shop domain without https, e.g. "my-store" or "my-store.myshopify.com"
SHOPIFY_SHOP = os.environ.get("SHOPIFY_SHOP", "aracacao.myshopify.com")
SHOPIFY_CLIENT_ID = os.environ.get(
    "SHOPIFY_CLIENT_ID",
    "",
)
SHOPIFY_CLIENT_SECRET = os.environ.get(
    "SHOPIFY_CLIENT_SECRET",
    "",
)
SHOPIFY_ACCESS_TOKEN = os.environ.get(
    "SHOPIFY_ACCESS_TOKEN",
    "",
)
# API version segment in URL path
SHOPIFY_API_VERSION = os.environ.get("SHOPIFY_API_VERSION", "2024-01")

# Financial status filter: any, paid, pending, authorized, partially_paid, etc.
SHOPIFY_FINANCIAL_STATUS = os.environ.get("SHOPIFY_FINANCIAL_STATUS", "paid")

# How far back to look for orders (hours). For "yesterday" daily job, 36–48 is safe.
SHOPIFY_LOOKBACK_HOURS = int(os.environ.get("SHOPIFY_LOOKBACK_HOURS", "48"))

# Max orders per run (safety)
SHOPIFY_MAX_ORDERS = int(os.environ.get("SHOPIFY_MAX_ORDERS", "50"))

# --- Softland ---
SOFTLAND_EXE_PATH = os.environ.get(
    "SOFTLAND_EXE_PATH",
    r"C:\Program Files\Softland\...\Softland.exe",
)
SOFTLAND_WINDOW_TITLE_SUBSTRING = os.environ.get(
    "SOFTLAND_WINDOW_TITLE_SUBSTRING",
    "softland cloud",
)
WINDOWS_APP_EXE_PATH = os.environ.get(
    "WINDOWS_APP_EXE_PATH",
    r"C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsApp_...\Windows App.exe",
)
WINDOWS_APP_WINDOW_TITLE_SUBSTRING = os.environ.get(
    "WINDOWS_APP_WINDOW_TITLE_SUBSTRING",
    "Windows App",
)
SOFTLAND_USER = os.environ.get("SOFTLAND_USER", "")
SOFTLAND_PASSWORD = os.environ.get("SOFTLAND_PASSWORD", "")

# Delays (seconds) — increase on slow PCs
DELAYS = {
    "after_launch": float(os.environ.get("DELAY_AFTER_LAUNCH", "12")),
    "between_keys": float(os.environ.get("DELAY_BETWEEN_KEYS", "0.05")),
    "between_clicks": float(os.environ.get("DELAY_BETWEEN_CLICKS", "0.4")),
    "after_tab": float(os.environ.get("DELAY_AFTER_TAB", "0.2")),
    "after_invoice_save": float(os.environ.get("DELAY_AFTER_INVOICE_SAVE", "2")),
}

# --- SKU mapping: Shopify variant SKU / line item SKU → Softland product code ---
# If empty, line item SKU is used as-is for Softland.
# Example: {"SHOPIFY-SKU-1": "SL-001", "T-SHIRT-M": "ART-99"}
SKU_MAP: dict[str, str] = {}

# --- Email notifications (optional) ---
SMTP_HOST = os.environ.get("SMTP_HOST", "")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
SMTP_USE_TLS = os.environ.get("SMTP_USE_TLS", "true").lower() in ("1", "true", "yes")
EMAIL_FROM = os.environ.get("EMAIL_FROM", "")
EMAIL_TO = os.environ.get("EMAIL_TO", "")  # comma-separated for multiple

# --- pyautogui ---
PYAUTOGUI_FAILSAFE = os.environ.get("PYAUTOGUI_FAILSAFE", "true").lower() in (
    "1",
    "true",
    "yes",
)

# If true, fetch Shopify orders and log actions without clicking Softland.
DRY_RUN = os.environ.get("DRY_RUN", "false").lower() in ("1", "true", "yes")
